### PR TITLE
try more potential mixer names

### PR DESCRIPTION
**Pull request by benklop**
I needed this to get volume controls to work with my JustBoom DAC pi hat.

### CODE REVIEW

**Comment by forslund** [comment]
Hi @benklop thanks for this contribution. From a glance it looks good and I'll test it out shortly.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by benklop** [comment]
@forslund Just signed. thanks!

**Comment by penrods** [comment]
I just double-checked and you requested the CLA but did not digitally sign it using HelloSign.  I resent the request for signature, it should be at the top of your email.  It should be from HelloSign and say it is a signature request from Joshua Montgomery.

**Comment by benklop** [comment]
Thanks @penrods, I really did sign it this time!

**Comment by forslund** [comment]
Sorry for the delay on this, I didn't see the update in the contributors list. Merging now!

**Pull request merged**
