### PR TITLE
Added setvolume (to default level) at startup

### PR DESCRIPTION
**Pull request by emphasize**
## Description
I realized that  given the system volume configuration isn’t the same as the default_level (set up by mycroft.config/VolumeSkill itself) there is no adjustment at the initialisation of the skill. And the mute/unmute situation will somewhat bypass the default_volume in that situation. (given the first `self.vol_before_mute = self.__get_system_volume()` ) mentioned on the [forums](https://community.mycroft.ai/t/volumeskill-and-setvolume-at-initialisation/9480)

This 5-liner PR adds a _setvolume call if  the system volume != the default_level and sets vol_before_mute accordingly

## Type of PR
Quick bugfix

## Test coverage
Tested with both [default_level](https://github.com/MycroftAI/skill-volume/blob/5777b2e57928247cf24d96267e55c123c5aa651c/__init__.py#L50) from the skill _init_ and default_level residing in .conf

## Documentation
comment docu

## Further Thoughts
At least locally i will add an intent to change the default_level over speech. (in exchange to editing .conf)
I use (the same) mycroft instance in several places (designed a slider case and docker stations) using different audio hardware, hence different vol levels.
Let me know if you consider this functionality (added intent) baseline so i would add this to this PR

### CODE REVIEW

**Comment by emphasize** [comment]
Shoot, immediate reversal of the test coverage statement:

It seems VolumeSkill doesn't care about

```
"VolumeSkill": {
    "default_level" : 10,
```
I recently made changes directly to __init__.py prior to this PR setting default_level to 10 and this still was sitting in settings.json as i reviewed the changes.

**Comment by emphasize** [comment]
Figured `self.settings.get('default_level')` should do the trick, but it ain't.

This does it:
```
if not self.config_core['VolumeSkill'].get('default_level'):
            vol_default = self.__level_to_volume(self.settings.get('default_level'))
else:
            vol_default = self.__level_to_volume(self.config_core['VolumeSkill'].get('default_level'))
```

**Comment by emphasize** [comment]
the origin of the volume set to 75% is to be found in the [auto_run.sh](https://github.com/MycroftAI/enclosure-picroft/blob/7d15a9ab47730b580e8eaec7363c7da40c04c45c/home/pi/auto_run.sh#L880)

**Comment by krisgesling** [comment]
Hey there,

We've just been talking about this Skill needing some restructuring to split out Skill functionality from system details which will change depending on what Mycroft is installed on. Eg on a Mark II we control the volume over I2C, may want a different default level, and can have different feedback for users than a Picroft has. Currently they're all handled a little differently and it's a bit of maze. It sounds like you've run into a similar issue, wanting different default levels for different types of devices.

As you've found there is no `default_level` config in the mycroft.conf at the moment, but this could be a good candidate for where the default value lives - presumably in the device level config `/etc/mycroft/mycroft.conf`?

The separate question is whether we want the default level to be set on each boot of the device. This might depend on the device too, eg more likely on a Mark II where reboots are rare and you want to ensure it's not muted. Compared to a desktop install where Mycroft may be stopped and started more frequently, independent of the broader system.

@dschweppe care to weigh in from a UX perspective on this?

**Comment by emphasize** [comment]
@krisgesling Refactoring the setup process, i imagine something along those lines

```
 JSON=$( cat /etc/mycroft/mycroft.conf | jq '.VolumeSkill = {"default_level": '"$lvl"', "min_volume": 0, "max_volume": '"$max"'}' )
 echo "$JSON" | sudo tee /etc/mycroft/mycroft.conf
```

 to be added to the setup process, ultimately substituting the [save_volume ](https://github.com/MycroftAI/enclosure-picroft/blob/afd739ebbaa7ee13204b2bfcf2103c1e5e8aa984/home/pi/auto_run.sh#L84)part -into audio_setup.sh- alltogether (which would increase the accessibility)

**Pull request closed without merging**
